### ISSUE TITLE
Reorganize inventory number fields

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#33]
Documentation and to do list for me:

- [x] new column `heid_inv_cat` (values: `p` (papyrus) / `o` (`material`=`ostrakon` or `holz`)
- [x] rename
  - `p_heid_inv -> heid_inv_spr`
  - `p_heid_inv_nr -> heid_inv_nr`
  - `p_heid_inv_buchstabe -> heid_inv_buchstabe`
  - `p_heid_inv_erg -> zusammensetzung_info` (see https://github.com/kadowa/papyri/issues/32#issuecomment-234205789)
- [x] restore changed record (see https://github.com/kadowa/papyri/issues/23#issuecomment-230740028)
- [ ] new columns
  - `dwork_id`, e.g. `p_g_30_a`
  - `inventarnummer`, e.g. `P. Heid. Inv. G. 30 a`

**Comment by jcowey** [comment]
`inventarnummer` concatenates value of `heid_inv_cat` spatium "Heid. Inv." value of `heid_inv_spr` spatium value of `heid_inv_nr`spatium value of `heid_inv_buchstabe` (if there is one, otherwise do nothing).
Your example above `P. Heid. Inv. 30 a` is not good.
There will be `P. Heid. Inv. G. 30`,  `P. Heid. Inv. Arab. 30`,  `P. Heid. Inv. Kopt. 30`, etc
so the value of `heid_inv_spr` must be  included.

**Comment by kadowa** [comment]
Sorry, forgot to add the `G.` there (corrected it above).

**Comment by jcowey** [comment]
Great. No problem!

**Comment by jcowey** [comment]
@kadowa Fantastic!! Thanks!! Can you please give me the all clear today so that I can make some progress on #29 and #31 without getting in the way of database restructuring.

**Comment by kadowa** [comment]
All clear! :rocket: :wink:
